/* We need this to make hibernate validation happy */
CREATE SEQUENCE hibernate_sequence START WITH 1 INCREMENT BY 1;

INSERT INTO USER (ID, USERNAME, PASSWORD) VALUES(1, 'Jeff', 'password123');
INSERT INTO USER (ID, USERNAME, PASSWORD) VALUES(2, 'Rod', 'SECURE');
INSERT INTO USER (ID, USERNAME, PASSWORD) VALUES(3, 'Alysa', 'Giraf');

INSERT INTO PERMS(permission, user_id) VALUES ('ListUsers', 1);
INSERT INTO PERMS(permission, user_id) VALUES ('Guardian', 1);

INSERT INTO AUTHTOKEN (ID, TOKEN, USER_ID) VALUES(1, 'FAKETOKEN', 1);
INSERT INTO AUTHTOKEN (ID, TOKEN, USER_ID) VALUES(2, 'MOBILETOKEN', 1);
INSERT INTO AUTHTOKEN (ID, TOKEN, USER_ID) VALUES(3, 'asdeg2:', 3);
