INSERT INTO USER (ID, username, password, department_id) VALUES (1337, 'Derp', 'hemmeligkode', 2);
INSERT INTO PERMS(permission, user_id) VALUES ('ListUsers', 1337);
INSERT INTO AUTHTOKEN (ID, TOKEN, USER_ID) VALUES(4, 'PICTOTOKEN', 1337);

INSERT INTO PictogramImage (ID, FILEPATH) VALUES(1, 'jeff');
INSERT INTO PictogramImage (ID, FILEPATH) VALUES(2, 'jeffyy');

INSERT INTO PICTOGRAM (ID, TITLE, LASTEDITAT, OWNER_ID, ACCESSLEVEL, PICTOGRAMIMAGE_ID, DEPARTMENT_ID) VALUES(1, 'test1', TIMESTAMP '2001-09-11 13:37:00', 1, 0, 1, 2);
INSERT INTO PICTOGRAM (ID, TITLE, LASTEDITAT, OWNER_ID, ACCESSLEVEL, PICTOGRAMIMAGE_ID, DEPARTMENT_ID) VALUES(2, 'test2', TIMESTAMP '2001-09-11 13:37:00', 1337, 2, 2, 2);
